version: 2
updates:
  - package-ecosystem: "ruby"
    directory: "/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "weekly"
