# Copyright (C) 2025 l5yth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "erb", "~> 4.0"
gem "sqlite3", "~> 1.7"
gem "rackup", "~> 2.2"
gem "puma", "~> 7.0"
gem "prometheus-client"

group :test do
  gem "rspec", "~> 3.12"
  gem "rack-test", "~> 2.1"
  gem "rufo", "~> 0.18.1"
  gem "simplecov", "~> 0.22", require: false
  gem "simplecov_json_formatter", "~> 0.1", require: false
  gem "rspec_junit_formatter", "~> 0.6", require: false
end
